/*
 * jLabel1 == "welcome to poker online"
 * jLabel2 == Texas Hold'em icon
 * jComboBox1 == choose game box
 * jButton1 == "OK" button
 * jButton2 == "Quit" 
 * 
 * 
 * 
 */
package client.view;

import common.*;
import images.*;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;


/**
 *
 * 
 */
public class Welcome extends javax.swing.JFrame {
    
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
    private boolean bGetGameList=false;
    private boolean quitGame=false;
    private String gameChoice=null;
    private String[] gamelist=null;
    private boolean bInit = false;
    
    public void resetGameList() {
    	if (bInit)
    	{
    		jComboBox1.setSelectedIndex(-1);
    		gameChoice=null;
    	}
    }
    
    public boolean isbGetGameList() {
		return bGetGameList;
	}

	public void setbGetGameList(boolean bGetGameList) {
		this.bGetGameList = bGetGameList;
	}

	public boolean isQuitGame() {
		return quitGame;
	}

	public void setQuitGame(boolean quitGame) {
		this.quitGame = quitGame;
	}

	public String getGameChoice() {
		return gameChoice;
	}

	public void setGameChoice(String gameChoice) {
		this.gameChoice = gameChoice;
	}

	public String[] getGamelist() {
		return gamelist;
	}

	public void setGamelist(String[] gamelist) {
		this.gamelist = gamelist;
	}

	
    /**
     * Creates new form welcome
     */
    public Welcome() {
    	bInit = false;
        update();
        bInit = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void update() {

    	if (!bInit)
    	{
    		buttonGroup1 = new javax.swing.ButtonGroup();
    		buttonGroup2 = new javax.swing.ButtonGroup();
    		buttonGroup3 = new javax.swing.ButtonGroup();
    		buttonGroup4 = new javax.swing.ButtonGroup();
    		jLabel1 = new javax.swing.JLabel();
    		jLabel2 = new javax.swing.JLabel();
    		jButton1 = new javax.swing.JButton();
    		jButton2 = new javax.swing.JButton();
    		jLabel3 = new javax.swing.JLabel();
    		jComboBox1 = new javax.swing.JComboBox();
    	}

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PokerOnline");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("images/holdem.jpeg"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        
        if(bGetGameList==false){
        	jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        	jLabel1.setText("Welcome to Poker Online! ");
        	jComboBox1.setVisible(false);
        } 
        else{
        	
        	jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(gamelist));
        	jComboBox1.setSelectedIndex(0);
        	jComboBox1.setVisible(true);
            jComboBox1.addActionListener(new java.awt.event.ActionListener() {
                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                     JComboBox gamebox=(JComboBox)evt.getSource();
                     gameChoice=(String)gamebox.getSelectedItem();
                 }
             });
        }
       jButton1.setVisible(false);
       jButton2.setVisible(false);

       

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 125, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 213, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 191, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(139, 139, 139))
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(24, 24, 24)
                        .add(jButton2))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .add(156, 156, 156)
                        .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(192, 192, 192)
                        .add(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(51, 51, 51)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 73, Short.MAX_VALUE)
                .add(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

public void popMessage(String msg){
	JOptionPane.showMessageDialog(this, msg );
}
// enter Texas Hold'em    


//game selection error



}
